### DISCUSSION TITLE
Postgresql data is seemingly not persisted

### DISCUSSION THREAD

**Discussion by nixonjoshua98** [kube-hetzner/terraform-hcloud-kube-hetzner#1337] [Q&A] [answered]
Hi, the issue I have currently is that /var/lib/postgresql is not being persisted across pod restarts but an added test file at /var/lib/postgresql/test is persisted between node switches and pod restarts and I dont understand why.

postgresql.deployment.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgresql-config
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql-pvc
```

postgresql-pvc.yaml
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  labels:
    app: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
```

postgresql-service.yaml
```yaml
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  clusterIP: None
  selector:
    app: postgresql
  ports:
    - port: 5432
```

Adding data to the database then restarting the pod causes all the changes to be lost, but adding a test file into the volume seems to persist. I can't seem to figure out why

---

![image](https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/assets/22799825/b07efcf4-e5d2-49f7-a2b6-0c296eb4f0f4)

**Comment by nixonjoshua98** [comment, marked as answer]
I have to set a subPath on the mount, and mount directly onto /data

```yaml
volumeMounts:
   - name: postgresql-data
     mountPath: /var/lib/postgresql/data
     subPath: postgresql
```
