### DISCUSSION TITLE
issues with custom storage classes? any idea?

### DISCUSSION THREAD

**Discussion by Gilaco** [kube-hetzner/terraform-hcloud-kube-hetzner#383] [Q&A] [answered]
Hey, 
I wondered if any of you tried to create custom StorageClass.

seems that when I tried to create my own class - it fails to provision the volumes; 
might be that I need to specify anything inside the kube.tf config?

this is the class that I tried to create... 
(when I refer my pvc to the default class created with the cluster if it provisioned ok... only custom not working)

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aerospike-sc
  labels:
    app: aerospike
provisioner: csi.hetzner.cloud
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  csi.storage.k8s.io/node-publish-secret-namespace: kube-system

```

really appreciate your help
thanks 
G
