### DISCUSSION TITLE
Why are random load balancers generated

### DISCUSSION THREAD

**Discussion by codeagencybe** [kube-hetzner/terraform-hcloud-kube-hetzner#400] [Q&A] [answered]
@mysticaltech 

Is this normal behaviour that the cluster is generating new load balancers adhoc? 
I have installed Prometheus and grafana, Kubecost and YygabyteDB from the Rancher app catalog. 
I can not remember that I did something special regarding LB or anything. In fact, in the Rancher shell it told me I needed to port forward stuff to see the web UI. 
But it doesn't make sense why it's generating new LB's adhoc as I already have 1 that should cover everything that needs to go into the cluster?  

![image](https://user-images.githubusercontent.com/7568546/200025586-f62c8fbd-2ea3-4821-ae39-7f987d64b61a.png)

**Comment by mysticaltech** [comment, marked as answer]
@codeagencybe Those might have been requested by the new helm charts you're now using. You can instead force them to use your ingress controller.

To verify the above hypothesis, just issue `kubectl get svc -A`, and you should see multiple LBs.

**Reply by fschrempf** [reply]
@mysticaltech I'm having the same problem as described above and I'm new to K8s. Can you give me a hint on how to force my helm charts to use the existing ingress controller? Thanks!

**Reply by mysticaltech** [reply]
@fschrempf You only need to dive into the values.yaml of your helm chart and tell it to use ingress definitions instead of deploying a LB service.

**Reply by fschrempf** [reply]
Ok, I'm still struggling to understand how to do that. I can disable the included ingress of the helm chart (I'm using the [bitnami nginx chart](https://github.com/bitnami/charts/tree/main/bitnami/nginx) for testing) by setting `ingress.enabled = false`.

I assume I could use `ingress.ingressClassName` to reference an `IngressClass` or create a default `IngressClass` for the Traefik LB!?
I tried to add something like below, but couldn't find out how to reference the existing Traefik ingress controller.

```
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    app.kubernetes.io/component: traefik
  name: traefik
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: ???
```
