### DISCUSSION TITLE
Pod can't connect to MongoDB outside the cluster.

### DISCUSSION THREAD

**Discussion by rviar** [kube-hetzner/terraform-hcloud-kube-hetzner#452] [Q&A] [answered]
Hello!
I have a problem with connecting to a database that is outside the cluster.
I can ping the server from the pod, but if i try communicate with 27017 port, then always get an error "Connection timed out".
Firewall on the monodb server is correct, and I can connect to database from other servers, but not from the cluster.

The result of curl command:

```
user@tmp-6666c75586-ffdmg:/home/node$ curl -v ***.***.***.***      
*   Trying ***.***.***.***:80...
* connect to ***.***.***.*** port 80 failed: Connection refused
* Failed to connect to ***.***.***.*** port 80: Connection refused
* Closing connection 0
curl: (7) Failed to connect to ***.***.***.*** port 80: Connection refused
```
Server with mongoDB close the connection because port 80 is closed, its ok.
If just ping the server also everything is work.

But when I try telnet or curl to port 27017 then I always get Timeout.

I'm try create NetworkPolicy like this:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-egress
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - {}
 ```

or this:

```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: egress-allow-internet-only
  namespace: default
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
    - ports:
        - protocol: TCP
          port: 27017
```
but didn't help...

I will be grateful for any help!
