### DISCUSSION TITLE
how to apply/add additional kustomize

### DISCUSSION THREAD

**Discussion by donydonald1** [kube-hetzner/terraform-hcloud-kube-hetzner#502] [Q&A] [answered]
Hello, 
   really new to kustomization. I would like to know how I can pass in additional deployment using the kustomize values that has been added to the module.
```
  # Extra values that will be passed to the `extra-manifests/kustomization.yaml.tpl` if its present.
  # extra_kustomize_parameters={}
```

**Comment by marsch** [comment, marked as answer]
think that might be something for the README or a wiki. I was struggling with the same issue. The way how I do it right now is just to add the  `extra-manifests/kustomization.yaml.tpl`

like so

```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./actionsrunner.yaml
  - ./airflow.yaml
```

and than define a `HelmCart` within the files. p.e.:

```
---
apiVersion: v1
kind: Namespace
metadata:
  name: airflow

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: apache-airflow
  namespace: airflow
spec:
  chart: airflow
  targetNamespace: airflow
  repo: https://airflow.apache.org
```

what's possible you can lookup here: https://docs.k3s.io/helm#using-the-helm-crd


hope that helps, cheers

**Reply by mashkovd** [reply]
_I have fail.
Firstly i create diretory **extra-manifests** with file kustomization.yaml.tpl_
```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./actionsrunner.yaml
  - ./airflow.yaml
  ---
apiVersion: v1
kind: Namespace
metadata:
  name: airflow

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: apache-airflow
  namespace: airflow
spec:
  chart: airflow
  targetNamespace: airflow
  repo: https://airflow.apache.org
```
  
  _after that i try fo command_ 
  `terraform apply -auto-approve`
  
  _and see next message_ 
  
  
```
-/+ resource "null_resource" "kustomization_user" {
      ~ id = "3705117395110404935" -> (known after apply)
    }

...
│ Error: remote-exec provisioner error
│ 
│   with module.kube-hetzner.null_resource.kustomization_user[0],
│   on .terraform/modules/kube-hetzner/kustomization_user.tf line 33, in resource "null_resource" "kustomization_user":
│   33:   provisioner "remote-exec" {
│ 
│ error executing "/tmp/terraform_862746133.sh": Process exited with status 1
```


What's my problem?
