### DISCUSSION TITLE
Traefik can't find endpoints

### DISCUSSION THREAD

**Discussion by v-petukhov** [kube-hetzner/terraform-hcloud-kube-hetzner#588] [Q&A] [answered]
Hey! 

I don't know how to name this question, so it named as it named...

Problem that traefik can not find any endpoints and logs contains such info:

```
traefik-74f488ccf-889sf time="2023-02-15T09:16:14Z" level=error msg="Skipping service: no endpoints found" serviceName=echo-service servicePort="&ServiceBackendPort{Name:,Number:80,}" providerName=kubernetes ingress=echo-server namespace=odysseus
traefik-74f488ccf-xzqzg time="2023-02-15T09:16:14Z" level=error msg="Skipping service: no endpoints found" serviceName=echo-service servicePort="&ServiceBackendPort{Name:,Number:80,}" providerName=kubernetes namespace=odysseus ingress=echo-server
traefik-74f488ccf-zc4mz time="2023-02-15T09:16:14Z" level=error msg="Skipping service: no endpoints found" servicePort="&ServiceBackendPort{Name:,Number:80,}" providerName=kubernetes ingress=echo-server namespace=odysseus serviceName=echo-service
```

I've achieved such result using simplest manifest:

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
        - name: echo-server
          image: jmalloc/echo-server
          ports:
            - name: http-port
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echo-service
spec:
  ports:
    - name: http-port
      port: 80
      targetPort: http-port
      protocol: TCP
  selector:
    app: echo-server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-server
  annotations:
    cert-manager.io/cluster-issuer: cluster-issuer
spec:
  tls:
    - hosts:
        - "poc.****.com"
      secretName: tls-poc-com-ingress-http
  rules:
    - host: "poc.****.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: echo-service
                port:
                  number: 80
```

Using such kubectl command to apply: 

`kubectl apply -f manifest.yaml -n odysseus`

Namespace "odysseus" already exists

Also, if I'm proxying ports to local machine I can access to `echo-service` (`kubectl port-forward service/echo-service 3000:80 --namespace odysseus`)

What is wrong with my cluster installation? I've already broke my brains... )) 

P.S. There are no any additional traefik options in `kube.tf` 

Thx in advance!
