### DISCUSSION TITLE
Autoscaler not adding node based on nodeSelector

### DISCUSSION THREAD

**Discussion by jonas-tm** [kube-hetzner/terraform-hcloud-kube-hetzner#597] [Q&A] [answered]
Hi, 
I am having issues with the autoscaler. 
I am trying to schedule a pod on an autoscaler node via nodeSelector. It is working fine when targeting the labels of agent node pool but when targeting an autoscale node pool (init pool size 0) autoscaler is not picking up the node.
Am I missing a certain config in `kube.tf` or is there a way to debug this to know why it is not scheduled?

Setup:
- kube-hetzner 1.9.1
- Kubernetes v1.25

Cluster Autoscaler logs
```log
I0219 17:57:56.723532       1 hetzner_node_group.go:437] Set node group draining-node-pool size from 0 to 0, expected delta 0
I0219 17:57:56.723568       1 hetzner_node_group.go:437] Set node group kube-hetzner-autoscaler-small size from 0 to 0, expected delta 0
I0219 17:57:56.724498       1 klogx.go:86] Pod my-app/my-app-54876b48c-vvm7f is unschedulable
I0219 17:57:56.724789       1 scale_up.go:462] No expansion options
I0219 17:57:56.724933       1 legacy.go:727] No candidates for scale down
```

Part of kube.tf
```hcl
  autoscaler_nodepools = [
    {
      name        = "autoscaler-small"
      server_type = "cpx21", # must be same or better than the control_plane server type (regarding disk size)!
      location    = "ash",
      labels = [
        "location=ash",
        "cores=3",
        "memory=4",
        "disk=40",
        "type=autoscaler",
        "size=small"
      ],
      min_nodes = 0
      max_nodes = 15
    },
```

Deployment YAML
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
  name: my-app
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
    spec:
      containers:
          image: 'myimage.com/myimage'
          imagePullPolicy: Always
          name: my-app
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources: {}
      nodeSelector:
        size: small
        type: autoscaler
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
# ....
```
