### DISCUSSION TITLE
Outbount SMTP on Port 465 not working

### DISCUSSION THREAD

**Discussion by michael-heuer** [kube-hetzner/terraform-hcloud-kube-hetzner#625] [Q&A] [answered]
Hi guys,

I really like this project and setup a cluster for testing. But I have a problem with one of the web applications which uses mails.

If I have egress traffic of port 25, 465, 993 I got a timeout. Egress traffic on ports like 80 443 8080 8443 works.

In the kube.tf if have set:
```
 restrict_outbound_traffic = false
 cni_plugin = "cilium"
```

I have tried it with no networkpolicy rules in the namespace the pod is running in and with a rule allowing anything.
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-egress
  namespace: test
spec:
  egress:
    - {}
  podSelector: {}
  policyTypes:
    - Egress
```

If I log into one of the nodes and try to use curl on other ports with this service `http://portquiz.net/` I can reach those port either. On my machine I can reach ports like 25 and 465 there.

I also double checked the Hetzner firewall rules. No outbound rules are set.

Do you have any idea how i can further debug the issue?
