### DISCUSSION TITLE
Hetzner CSI Persistent Volume Claims stay in pending

### DISCUSSION THREAD

**Discussion by jonas-tm** [kube-hetzner/terraform-hcloud-kube-hetzner#627] [Q&A]
Hi,
 I am trying to provision a persistent volume. I am using the default setup with Hetzner CSI controller.
However, when provisioning a simple volume (see yaml below) it stays in pending state.
I also checked the logs of the Hetzner CSI Controller, but it is not showing anything. 
Am I missing a certain configuration?

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hcloud-volumes

```
