### DISCUSSION TITLE
SMB Volume encryption

### DISCUSSION THREAD

**Discussion by Lennix** [kube-hetzner/terraform-hcloud-kube-hetzner#782] [Q&A]
I've noticed you've integrated csi-driver-smb to connect to storage-boxes. I got this setup running for a couple months now for (very) cheap storage and it works pretty good. The connection gets dropped some times and you have to re-spawn the pod to reconnect, but overall its fine.

I also noticed that you worked out encryption for longhorn and hetzner-csi and I was wondering if the same could be achieved for the smb driver?

Since the smb traffic is unencrypted, this sounds like a very interesting use case to me.

**Comment by mysticaltech** [comment]
@aleksasiriski You are probably more familiar with that use case!

**Reply by aleksasiriski** [reply]
I haven't experienced any drops in connection with my settings which I will share as soon as I get to my PC.

I'll look into implementing encryption at REST.

**Reply by aleksasiriski** [reply]
Here are my settings for Storage Box CIFS/SMB:

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-box
  namespace: default
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
spec:
  capacity:
    storage: 5Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=568
    - gid=568
    - vers=3.0
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: uXXXXXX.your-storagebox.de/backup##
    volumeAttributes:
      source: "//uXXXXXX.your-storagebox.de/backup"
    nodeStageSecretRef:
      name: storage-box-credentials
      namespace: default
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: storage-box
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Ti
  volumeName: storage-box
  storageClassName: smb
```
