### ISSUE TITLE
[Bug]: Hetzner secret is empty

### ISSUE THREAD

**Issue by gthieleb** [kube-hetzner/terraform-hcloud-kube-hetzner#1632]
### Description

When deploying a kube hetzner with tofu recent version v2.16.1 the hcloud secret is empty. 

The network name is created:

```
k -n kube-system get secrets hcloud -oyaml
apiVersion: v1
data:
  network: c3RhZ2luZw==
  token: ""
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"network":"c3RhZ2luZw==","token":""},"kind":"Secret","metadata":{"annotations":{},"creationTimestamp":null,"name":"hcloud","namespace":"kube-system"}}
  creationTimestamp: "2025-02-12T13:00:44Z"
```

The secret is created in the init step.

versions:

```
tofu -version
OpenTofu v1.9.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.4
+ provider registry.terraform.io/hashicorp/local v2.5.1
+ provider registry.terraform.io/hashicorp/null v3.2.2
+ provider registry.terraform.io/hashicorp/random v3.6.1
+ provider registry.terraform.io/hetznercloud/hcloud v1.46.1
+ provider registry.terraform.io/integrations/github v6.2.1
+ provider registry.terraform.io/tenstad/remote v0.1.3
```

### Kube.tf file

```terraform
tbd
```

### Platform

Linux
