### ISSUE TITLE
[Feature Request]: Add ability deploy multiple Loadbalancers

### ISSUE THREAD

**Issue by garry-t** [kube-hetzner/terraform-hcloud-kube-hetzner#1718]
### Description

Hetzner loadbalancers have bandwidth limitation 1Gb network card, for highload projects is it not suitable. Having ability to deploy multiple balancers can improve bandwidth

**Comment by mysticaltech** [comment]
@garry-t You can do so by using services of type LoadBalancer. That's a feature of kubernetes. 

```
# svc-lb1.yaml
apiVersion: v1
kind: Service
metadata:
  name: myapp-lb1
  annotations:
    # this controls what Hetzner calls it in their API/UI
    load-balancer.hetzner.cloud/name: myapp-lb1
    # pick whatever LB size you need (lb11 is the 1 Gb/s default)
    load-balancer.hetzner.cloud/type: lb11
spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
# svc-lb2.yaml
apiVersion: v1
kind: Service
metadata:
  name: myapp-lb2
  annotations:
    load-balancer.hetzner.cloud/name: myapp-lb2
    load-balancer.hetzner.cloud/type: lb11
spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
  - name: http
    port: 80
    targetPort: 8080

```
