### ISSUE TITLE
Extend Rancher-support to allow bootstrapping

### ISSUE THREAD

**Issue by strowi** [kube-hetzner/terraform-hcloud-kube-hetzner#209]
Hi,

@mysticaltech would you be open to modifying the `rancher.yaml.tmpl` to allow for 2 more variables like  the following?

```yaml
  valuesContent: |-
    ingress:
      tls:
        source: ${rancher_tls_source}
    hostname: ${rancher_hostname}
    replicas: ${number_control_plane_nodes}
    bootstrapPassword: ${rancher_bootstrap_password}
```

That would allow to set the `bootstrapPassword` and complete the setup (if the variable is set outside the module) by code instead of manually having to check the container logs for the `bootstrapPassword`. 

BTW i had some trouble getting the rancher-import working when the `ingress.tls.source´ was rancher - since `kubectl apply -k..` would fail with a TLS-error. Only way to circumvent was to use `curl -k .. | k apply ..` or save the file locally in `/var/post_install`.
