### ISSUE TITLE
move traefik /api to another route

### ISSUE THREAD

**Issue by digitalbuddha** [kube-hetzner/terraform-hcloud-kube-hetzner#514]
Hi folks. I was able to get up and running. Next, I created an ingress for my / route

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mastodon-web-traefik
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: "androiddevsocial.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mastodon2-web
            port: http
            port:
              number: 80
```

Next, I wanted to add a route for api/streaming which is required by one of my apps. I was unable to because /api seems to resolve to the traefik dashboard. Is there a way to change the route that goes to api@internal? 

Thank you for your help
