### ISSUE TITLE
How to install additional packages - installing Longhorn after creating cluster

### ISSUE THREAD

**Issue by aleksasiriski** [kube-hetzner/terraform-hcloud-kube-hetzner#516]
Is there a way to specify additional packages to be installed on all nodes? For example, when installing longhorn with helm manually it fails since the "check env" script says `nfs-client is not found in agent-small` and `open-iscsi is not found in agent-small`.

**Comment by mysticaltech** [comment]
In kube.tf, search for "package" and you will find the variable that can help you do that.

However, the packages you are mentioning are already installed.

What version are you using?

Please share your kube.tf without comments and sensitive data.

**Comment by aleksasiriski** [comment]
```
locals {
  hcloud_token = "*********"
}

module "kube-hetzner" {
  providers = {
    hcloud = hcloud
  }
  hcloud_token = local.hcloud_token

  source = "kube-hetzner/kube-hetzner/hcloud"

  ssh_public_key = file("~/.ssh/id_rsa.pub")
  ssh_private_key = file("~/.ssh/id_rsa")

  network_region = "eu-central"

  control_plane_nodepools = [
    {
      name        = "control-plane-nbg1",
      server_type = "cpx11",
      location    = "nbg1",
      labels      = [],
      taints      = [],
      count       = 1
    },
    {
      name        = "control-plane-fsn1",
      server_type = "cpx11",
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 1
    },
    {
      name        = "control-plane-hel1",
      server_type = "cpx11",
      location    = "hel1",
      labels      = [],
      taints      = [],
      count       = 1
    }
  ]

  agent_nodepools = [
    {
      name        = "agent-small-nbg1",
      server_type = "cpx21",
      location    = "nbg1",
      labels      = [],
      taints      = [],
      count       = 1
    },
    {
      name        = "agent-small-fsn1",
      server_type = "cpx21",
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 1
    }
  ]

  load_balancer_type     = "lb11"
  load_balancer_location = "nbg1"

  base_domain = "*********"

  initial_k3s_channel = "v1.25"

  cluster_name = "*********"

  extra_firewall_rules = [
    # Disable outbound rules
    {
      direction       = "out"
      protocol        = "tcp"
      port            = "any"
      source_ips      = []
      destination_ips = ["0.0.0.0/0", "::/0"]
    },
    {
      direction       = "out"
      protocol        = "udp"
      port            = "any"
      source_ips      = []
      destination_ips = ["0.0.0.0/0", "::/0"]
    },
    {
      direction       = "out"
      protocol        = "icmp"
      port            = ""
      source_ips      = []
      destination_ips = ["0.0.0.0/0", "::/0"]
    }
  ]

  enable_cert_manager = true

  # use_control_plane_lb = true

}

provider "hcloud" {
  token = local.hcloud_token
}

terraform {
  required_version = ">= 1.3.3"
  required_providers {
    hcloud = {
      source  = "hetznercloud/hcloud"
      version = ">= 1.35.2"
    }
  }
}

output "kubeconfig" {
  value     = module.kube-hetzner.kubeconfig
  sensitive = true
}
```

**Comment by aleksasiriski** [comment]
> In kube.tf, search for "package" and you will find the variable that can help you do that.

### ADVANCED - Custom helm values for **package**s above (search _values if you want to located where those are mentioned upper in this file)

**Comment by aleksasiriski** [comment]
Now traefik, installed by default and not tampered with, randomly gives "Forbidden" for all of my ingresses.

**Comment by aleksasiriski** [comment]
I guess [this](https://longhorn.io/docs/1.4.0/deploy/install/#installing-open-iscsi) can't work since it's expecting normal zypper (logs say it can't be found) but I guess that's to be expected since MicroOS probably uses something else (maybe similar to rpm-ostree on CoreOS?)

**Comment by mysticaltech** [comment]
@aleksasiriski We take care of all of this for you. First of all, those packages are already installed. All the packages need by Longhorn are installed already!

Please make sure to use the latest version by doing "terraform init -upgrade".

Now in very rare cases, you do need to install things, then you can use the "extra_packages_to_install" variable.

If you are curious, under the hood this uses transactional-update which in turns uses zypper.

**Comment by aleksasiriski** [comment]
I looked at your sourced and confirmed that those pkgs are installed indeed.

I tried applying this:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: longhorn-crd
  namespace: kube-system
spec:
  chart: longhorn-crd
  repo: https://charts.rancher.io
  targetNamespace: longhorn-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: longhorn
  namespace: kube-system
spec:
  chart: longhorn
  repo: https://charts.rancher.io
  targetNamespace: longhorn-system
  valuesContent: |-
    defaultSettings:
      defaultDataPath: /var/longhorn
    persistence:
      defaultFsType: ext4
      defaultClassReplicaCount: 3
      defaultClass: false
```

And it spits out this error sadly:
```bash
Error: INSTALLATION FAILED: chart requires kubeVersion: >=1.18.0-0 <1.25.0-0 which is incompatible with Kubernetes v1.25.5+k3s2
```
