### ISSUE TITLE
Autoscaler not scaling

### ISSUE THREAD

**Issue by AlexProgrammerDE** [kube-hetzner/terraform-hcloud-kube-hetzner#537]
Hello! I've been trying out this project and didn't manage to get autoscaling working. When my pods try to deploy, it just tells me that only two nodes are available, one of them is the control panel and the other one the first agent. 
My config uses these values:
```toml
control_plane_nodepools = [
    {
      name        = "control-plane-nbg1",
      server_type = "cpx11",
      location    = "nbg1",
      labels      = [],
      taints      = [],
      count       = 1
    }
  ]

  agent_nodepools = [
    {
      name        = "agent-large",
      server_type = "cx51",
      location    = "nbg1",
      labels      = [],
      taints      = [],
      count = 1
    }
  ]
  # Add custom control plane configuration options here.
  # E.g to enable monitoring for etcd, proxy etc:
  control_planes_custom_config = {
   etcd-expose-metrics = true,
   kube-controller-manager-arg = "bind-address=0.0.0.0",
   kube-proxy-arg ="metrics-bind-address=0.0.0.0",
   kube-scheduler-arg = "bind-address=0.0.0.0",
  }

  # * LB location and type, the latter will depend on how much load you want it to handle, see https://www.hetzner.com/cloud/load-balancer
  load_balancer_type     = "lb11"
  load_balancer_location = "nbg1"

  # Cluster Autoscaler
  # Providing at least one map for the array enables the cluster autoscaler feature, default is disabled
  # Please note that the autoscaler should not be used with initial_k3s_channel < "v1.25". So ideally lock it to "v1.25".
  # * Example below:
  autoscaler_nodepools = [
    {
      name        = "autoscaler"
      server_type = "cpx11" # must be same or better than the control_plane server type (regarding disk size)!
      location    = "nbg1"
      min_nodes   = 1
      max_nodes   = 5
    }
  ]
```
These are the currently deployed servers:
![image](https://user-images.githubusercontent.com/40795980/214650873-8fb5b44e-30f9-4cb0-afda-66a28d9e0dca.png)
It appears that the server for autoscaling is missing. I am using the latest version 1.8.1.
The terraform config applies without any errors:
```
module.kube-hetzner.data.github_release.hetzner_csi[0]: Reading...
module.kube-hetzner.data.github_release.hetzner_ccm[0]: Reading...
module.kube-hetzner.data.github_release.kured[0]: Reading...
module.kube-hetzner.random_password.k3s_token: Refreshing state... [id=none]
module.kube-hetzner.random_password.rancher_bootstrap[0]: Refreshing state... [id=none]
module.kube-hetzner.data.hcloud_servers.autoscaled_nodes["autoscaler"]: Reading...
module.kube-hetzner.hcloud_placement_group.agent[0]: Refreshing state... [id=118111]
module.kube-hetzner.hcloud_ssh_key.k3s[0]: Refreshing state... [id=9851167]
module.kube-hetzner.data.hcloud_ssh_keys.keys_by_selector[0]: Reading...
module.kube-hetzner.hcloud_network.k3s: Refreshing state... [id=2442188]
module.kube-hetzner.hcloud_placement_group.control_plane[0]: Refreshing state... [id=118112]
module.kube-hetzner.hcloud_firewall.k3s: Refreshing state... [id=693380]
module.kube-hetzner.data.hcloud_ssh_keys.keys_by_selector[0]: Read complete after 0s [id=xxx]
module.kube-hetzner.data.hcloud_servers.autoscaled_nodes["autoscaler"]: Read complete after 0s [id=da39a3ee5e6b4b0d3255bfef95601890afd80709]
module.kube-hetzner.data.github_release.hetzner_csi[0]: Read complete after 0s [id=89711362]
module.kube-hetzner.data.github_release.kured[0]: Read complete after 0s [id=86062001]
module.kube-hetzner.data.github_release.hetzner_ccm[0]: Read complete after 1s [id=79020566]
module.kube-hetzner.hcloud_network_subnet.control_plane[0]: Refreshing state... [id=2442188-10.255.0.0/16]
module.kube-hetzner.hcloud_network_subnet.agent[0]: Refreshing state... [id=2442188-10.0.0.0/16]
module.kube-hetzner.module.agents["0-0-agent-large"].random_string.identity_file: Refreshing state... [id=c1ayyaic8t1bu9ehqsrk]
module.kube-hetzner.module.agents["0-0-agent-large"].random_string.server: Refreshing state... [id=abo]
module.kube-hetzner.module.control_planes["0-0-control-plane-nbg1"].random_string.server: Refreshing state... [id=zew]
module.kube-hetzner.module.control_planes["0-0-control-plane-nbg1"].random_string.identity_file: Refreshing state... [id=nigvg3zcta1ujdo5ttpp]
module.kube-hetzner.module.agents["0-0-agent-large"].data.cloudinit_config.config: Reading...
module.kube-hetzner.module.agents["0-0-agent-large"].data.cloudinit_config.config: Read complete after 0s [id=2073267425]
module.kube-hetzner.module.agents["0-0-agent-large"].hcloud_server.server: Refreshing state... [id=27972432]
module.kube-hetzner.module.control_planes["0-0-control-plane-nbg1"].data.cloudinit_config.config: Reading...
module.kube-hetzner.module.control_planes["0-0-control-plane-nbg1"].data.cloudinit_config.config: Read complete after 0s [id=280194929]
module.kube-hetzner.module.control_planes["0-0-control-plane-nbg1"].hcloud_server.server: Refreshing state... [id=27972433]
module.kube-hetzner.module.agents["0-0-agent-large"].null_resource.registries: Refreshing state... [id=7315229217177627871]
module.kube-hetzner.module.agents["0-0-agent-large"].hcloud_server_network.server: Refreshing state... [id=27972432-2442188]
module.kube-hetzner.module.agents["0-0-agent-large"].hcloud_rdns.server[0]: Refreshing state... [id=s-27972432-x.x.x.x]
module.kube-hetzner.module.control_planes["0-0-control-plane-nbg1"].hcloud_rdns.server[0]: Refreshing state... [id=s-27972433-x.x.x.x]
module.kube-hetzner.module.control_planes["0-0-control-plane-nbg1"].hcloud_server_network.server: Refreshing state... [id=27972433-2442188]
module.kube-hetzner.module.control_planes["0-0-control-plane-nbg1"].null_resource.registries: Refreshing state... [id=6423485608408018346]
module.kube-hetzner.null_resource.first_control_plane: Refreshing state... [id=7070802316778084546]
module.kube-hetzner.hcloud_snapshot.autoscaler_image[0]: Refreshing state... [id=97394711]
module.kube-hetzner.data.cloudinit_config.autoscaler-config[0]: Reading...
module.kube-hetzner.null_resource.kustomization: Refreshing state... [id=2641344090826294402]
module.kube-hetzner.null_resource.agents["0-0-agent-large"]: Refreshing state... [id=9218326134874302650]
module.kube-hetzner.null_resource.control_planes["0-0-control-plane-nbg1"]: Refreshing state... [id=8516690779649704765]
module.kube-hetzner.data.cloudinit_config.autoscaler-config[0]: Read complete after 0s [id=3791662826]
module.kube-hetzner.data.hcloud_load_balancer.cluster[0]: Reading...
module.kube-hetzner.data.remote_file.kustomization_backup: Reading...
module.kube-hetzner.null_resource.destroy_cluster_loadbalancer: Refreshing state... [id=4664514048567351556]
module.kube-hetzner.data.remote_file.kubeconfig: Reading...
module.kube-hetzner.data.hcloud_load_balancer.cluster[0]: Read complete after 0s [name=horizon]
module.kube-hetzner.null_resource.configure_autoscaler[0]: Refreshing state... [id=7199351183629787419]
module.kube-hetzner.data.remote_file.kustomization_backup: Read complete after 1s [id=x.x.x.x:22:/var/post_install/kustomization.yaml]
module.kube-hetzner.data.remote_file.kubeconfig: Read complete after 1s [id=x.x.x.x:22:/etc/rancher/k3s/k3s.yaml]
module.kube-hetzner.local_sensitive_file.kubeconfig[0]: Refreshing state... [id=1765eebe4cd1e614b91891f952a5fc68a31003d3]
module.kube-hetzner.local_file.kustomization_backup[0]: Refreshing state... [id=62c320e17ab5f99388d5b1b2c5a17cfa7564e67d]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

kubeconfig = <sensitive>
```
These are the logs of cluster-autoscaler:
![image](https://user-images.githubusercontent.com/40795980/214651543-5f7997a0-7598-453c-ad60-719f69cf8f03.png)
And here is the error for the pods that can't start:
![image](https://user-images.githubusercontent.com/40795980/214651702-08a34304-da31-4650-a261-499b0869c5a1.png)
It appears that the autoscaler server was not deployed and so doesn't start new nodes.
I am using the HorizontalPodAutoscaler, but setting replicas manually on the deployment didn't work either.
I know when I first tried this project, there was a machine that had the name "autoscaler" inside it's name. With the newest versions, that machine just doesn't exist. No errors. And kubernetes finds no way of deploying more nodes. What could be the issue?

**Comment by mysticaltech** [comment]
@AlexProgrammerDE Please re-read the Autoscaling section in the readme. it says _The nodes are booted based on a snapshot that is created from the initial control_plane. So please ensure that the disk of your chosen server type is at least the same size as the one of the first control_plane._

Fix this, and you should be good!

**Comment by captnCC** [comment]
@mysticaltech Both are cpx11 instances, so it should work in theory 🤔

The limited logs give me the impression, that the autoscaler thinks there is no way to scale up the cluster.

**Comment by AlexProgrammerDE** [comment]
The entire autoscaler machine isn't even deployed to hcloud. I understood the autoscaler machine as a type of manager for deploying more nodes to the cluster? It doesn't appear to exist. The snapshot exists though.

**Comment by mysticaltech** [comment]
Yes @captnCC, when I realized that I deleted my comment. 

@AlexProgrammerDE Are you actually definition workload requirements in your pods and/or deployments? Because this is a must. See https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/pull/353#issue-1411712748

FYI @ifeulner.

**Comment by AlexProgrammerDE** [comment]
@mysticaltech yes, here is my kubernetes file I made:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multipaper
  labels:
    app: multipaper
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: 1
  selector:
    matchLabels:
        app: multipaper
  template:
    metadata:
      labels:
          app: multipaper
    spec:
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: mp-files
          nfs:
            server: 10.255.0.2
            path: /nfs/multipaper
            readOnly: no
      terminationGracePeriodSeconds: 10
      containers:
        - name: multipaper
          image: alexprogrammerde/multipaper-kubernetes:multipaper
          tty: true
          imagePullPolicy: Always
          resources:
            requests:
              memory: "16Gi"
              cpu: "4"
            limits:
              memory: "16Gi"
              cpu: "18"
          volumeMounts:
            - name: mp-files
              mountPath: /files
          ports:
            - name: game-port
              containerPort: 25565
          readinessProbe:
            exec:
              command:
                - mcstatus
                - 127.0.0.1
                - ping
            initialDelaySeconds: 30
            periodSeconds: 30
          livenessProbe:
            exec:
              command:
                - mcstatus
                - 127.0.0.1
                - ping
            initialDelaySeconds: 30
            periodSeconds: 30
          env:
            - name: KN_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: KN_POD_IP
              value: 0.0.0.0
            - name: MASTER_ADDRESS
              value: "10.255.0.2:35353"
            - name: USE_RAM
              value: "14G"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: multipaper-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: multipaper
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
```
