### ISSUE TITLE
feature request: Nodepools

### ISSUE THREAD

**Issue by exocode** [kube-hetzner/terraform-hcloud-kube-hetzner#65]
### Feature Nodepools

In the current form, it's only possible to create a cluster with equally sized nodes. 
It would be great to have be able to have **different sized nodes** like this:

```yaml
  pools:
    - id: "memory-pool"
      count: 3
      size: CX51
    - id: "worker-pool"
      count: 8
      size: CX11
```

If we like to go further, it's maybe possible to spead the cluster into **different physical locations** too. But I think that would be a really hard nut, because of private networks asf.

```yaml
  pools:
    - id: "memory-pool"
      location: "fsn1"
      count: 3
      size: CX51
    - id: "worker-pool"
      location: "hel1"
      count: 8
      size: CX11
```
