### ISSUE TITLE
[Bug]: Image pulling from private registry does not work on ARM nodes

### ISSUE THREAD

**Issue by henrydays** [kube-hetzner/terraform-hcloud-kube-hetzner#791]
### Description

Image pulling from private repositories (gitlab in my case) is not working on ARM nodes. 

The first example manifest as expected. It runs successfully on x86 nodes (nodeSelector amd64). 
```
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  nodeSelector:
    kubernetes.io/arch: amd64
  imagePullSecrets:
    - name: gitlabkey
  containers:
    - name: web
      image: registry.gitlab.com/henrydays/service:0.0.1
```

The ARM64 version does not work. It fails with `Error: ErrImagePull dial tcp 35.227.35.254:443: i/o timeout` error. 
```
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  nodeSelector:
    kubernetes.io/arch: arm64
  imagePullSecrets:
    - name: gitlabkey
  containers:
    - name: web
      image: registry.gitlab.com/henrydays/service:0.0.1
```
And yes, the image I am pulling is multi architecture. It also works in a microk8s cluster deployed on a Hetzner ARM instance.

### Kube.tf file

```terraform
locals {

  hcloud_token = ""
}

module "kube-hetzner" {
  providers = {
    hcloud = hcloud
  }
  hcloud_token = var.hcloud_token != "" ? var.hcloud_token : local.hcloud_token

  source = "kube-hetzner/kube-hetzner/hcloud"

  ssh_public_key = file("~/.ssh/id_ed25519.pub")
  ssh_private_key = file("~/.ssh/id_ed25519")
 
  network_region = "eu-central" 

  control_plane_nodepools = [
    {
      name        = "control-plane-fsn1",
      server_type = "cpx11",
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 1
    },
    {
      name        = "control-plane-nbg1",
      server_type = "cpx11",
      location    = "nbg1",
      labels      = [],
      taints      = [],
      count       = 1
    },
    {
      name        = "control-plane-hel1",
      server_type = "cpx11",
      location    = "hel1",
      labels      = [],
      taints      = [],
      count       = 1
    }
  ]

  agent_nodepools = [
    {
      name        = "agent-x86-small-node-pool-1",
      server_type = "cx51",
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 1
    },
    {
      name        = "agent-arm-small-node-pool-1",
      server_type = "cax41",
      location    = "fsn1",
      labels      = [],
      taints      = [],
      count       = 1
    }
  ]
  load_balancer_type     = "lb11"
  load_balancer_location = "fsn1"
  dns_servers = ["1.1.1.1","8.8.8.8"]
  cni_plugin = "calico"
  use_control_plane_lb = true
}

provider "hcloud" {
  token = var.hcloud_token != "" ? var.hcloud_token : local.hcloud_token
}

terraform {
  required_version = ">= 1.3.3"
  required_providers {
    hcloud = {
      source  = "hetznercloud/hcloud"
      version = ">= 1.38.2"
    }
  }
}

output "kubeconfig" {
  value     = module.kube-hetzner.kubeconfig
  sensitive = true
}

variable "hcloud_token" {
  sensitive = true
  default   = ""
}
```

### Platform

Linux
